controller_manager:
  ros__parameters:
    update_rate: 50

joint_state_broadcaster:
  ros__parameters:
    type: joint_state_broadcaster/JointStateBroadcaster
    publish_rate: 50

joint_trajectory_controller:
  ros__parameters:
    type: joint_trajectory_controller/JointTrajectoryController
    joints:
      - joint1
      - joint2
      - joint3
    state_publish_rate: 25
    action_monitor_rate: 10
    allow_partial_joints_goal: false
    constraints:
      goal_time: 0.6
      stopped_velocity_tolerance: 0.02
